### ISSUE TITLE
Filterring Workflows

### ISSUE THREAD

**Issue by ABakumenko** [ITDSystems/alvex-workflow-shortcut-dashlet#21]
Hello,
I have workFlow dashBoard on my site Home Page. And I have one filter button and one sort, but they don't work? I have Alfresco Community v5.2.0 and alvex-3.0-20170502.123755-241.zip

**Comment by aviriel** [comment]
Is not a bug of workflow-permissions component

**Comment by ABakumenko** [comment]
And why it doesn't work?
